input("give me a word!")
print()
input("give me a second word!")
print()
input(str("give me your favourite number!"))
print()
input(str("now give me your second favourite number!"))
print()
print ("whew, wasnt that fun!?")