print ("Hello there! please enter your information so I can sell it online for money!")
first_name = input("What is your first name?")
last_name = input("What is your last name?")
grade = int(input("What grade are you?"))
student_id = int(input("What is your student ID?"))
login = input("What is your login information?")
password = input("What is your password?")
average = input("What is your average?")

print("Your valuable information:")
print (f"   first name: {first_name}")
print (f"   last name: {last_name}")
print (f"   grade: {grade}")
print (f"   student id: {student_id}")
print (f"   login: {login}")
print (f"   password: {password}")
print (f"   average: {average}")
print ("you dumbo now im going to sell your identity! haha")